#list samostalnikov
listBesed = [
    "abak", "abakus", "Abdija", "abdikacija", "abeceda", "abecednik", "aberacija", "ablativ", 
    "abonent", "abonma", "abortus", "absolutizem", "aceton", "aforizem", "Afrika", "agava", 
    "Agej", "agrikultura", "agronomija", "ahat", "AIDS", "ajda", "ajnštajnij", "akacija", 
    "akademija", "akant", "akna", "akronim", "akrostih", "aksiom", "akt", "aktinij", 
    "akustika", "akuzativ", "akvamarin", "akvarel", "akvarij", "akvedukt", "alabaster", 
    "Albanec", "albanščina", "albatros", "albumin", "alegorija", "alergija", "alfa", 
    "alga", "algebra", "aligator", "aliteracija", "alkimija", "alkohol", "aloa", "alpaka", 
    "alt", "aluminij", "ambrozija", "americij", "Amerika", "ametist", "amfibrah", "amfiteater", 
    "amfora", "amharščina", "amoniak", "Amos", "amper", "amplituda", "amulet", "anafora", 
    "anagram", "anakonda", "analni seks", "analogija", "ananas", "anapest", "anarhija", 
    "anarhist", "anarhizem", "anatomija", "anekdota", "angel", "angina", "angleščina", 
    "Anglež", "anglikanec", "animist", "animizem", "anion", "anoda", "anorak", "antanta", 
    "antena", "antibiotik", "anticiklon", "antifona", "antilopa", "antimon", "antologija", 
    "antonim", "antonimija", "antracit", "antraks", "antropolog", "antropologija", "aorta", 
    "Apač", "apnenec", "apno", "apokalipsa", "apokopa", "apostol", "apostolska dela", 
    "apostrof", "april", "apsida", "Arabec", "arabeska", "arabščina", "aramejščina", 
    "arašid", "aravkarija", "arboretum", "Argentinec", "argon", "arheolog", "arheologija", 
    "arhipelag", "arhitekt", "arhitektura", "arhitrav", "arhiv", "arhivar", "arijanec", 
    "arijanstvo", "arkada", "Armenec", "armenščina", "arnika", "aroma", "artefakt", 
    "arterija", "artičoka", "artilerija", "artritis", "arzen", "as", "asfalt", "asonanca", 
    "astat", "asteroid", "astrofizika", "astrolab", "astronavt", "astronom", "astronomija", 
    "ateizem", "atletika", "atmosfera", "atol", "atom", "atribut", "atrij", "Avar", 
    "avenija", "avgust", "avokado", "Avstrijec", "avtizem", "avto", "avtobus", "avtomat", "avtocesta", 
    "avtonomija", "azaleja", "azbest", "Azija", "azil", "Aztek", "babica", "bajonet", 
    "baker", "bakla", "bakterija", "bala", "balalajka", "balerina", "balet", "baletnik", 
    "balon", "balustrada", "balvan", "balzam", "bambus", "banana", "bananovec", "banka", 
    "baptisterij", "barbar", "bard", "baretka", "barij", "bariton", "barok", "barva", "baržun", "bas", "basen", "Bask", 
    "baskovščina", "bat", "bataljon", "baterija", "batiskaf", "baza", "bazalt", 
    "bazar", "bazen", "bazilika", "beatifikacija", "bedak", "bedro", "beg", 
    "begonija", "begunec", "Belgijec", "belina", "beljak", "Beljak", "belo vino", 
    "beločnica", "beloruščina", "beluš", "bencin", "benediktinec", "benzen", "berač", 
    "bergla", "berilij", "berimbau", "berkelij", "bes", "beseda", "besedilo", 
    "besedišče", "beton", "bezeg", "biatlon", "bibavica", "biblija", "biceps", 
    "bič", "bienale", "bik", "bikoborba", "bilijarda", "biofizika", "biokemija", 
    "biolog", "biologija", "biotehnologija", "birma", "biser", "bitje", "bitka", 
    "bivak", "bivol", "bizmut", "bizon", "blagoslov", "blato", "blazina", 
    "blodnjak", "bluza", "bob", "boben", "bober", "bobnar", "bobnič", "bodalo", 
    "bog", "bogastvo", "boginja", "bogokletstvo", "bogomolka", "boj", "boja", 
    "bok", "boks", "boksar", "bol", "bolečina", "bolezen", "Bolgar", 
    "bolgarščina", "bolha", "Bolivijec", "boljševik", "bolnica", "bolnik", 
    "bomba", "bombardiranje", "bombaž", "bombnik", "bor", "bordel", "borij", 
    "borovnica", "Bosanec", "bosanščina", "botanik", "botanika", "boter", 
    "botra", "božanstvo", "božič", "božjast", "brada", "bradavica", "bralec", 
    "brana", "branilec", "brat", "bratovščina", "bratranec", "brazgotina", 
    "Brazilec", "brca", "breča", "breme", "breskev", "brest", "Bretonec", 
    "breza", "brezno", "brglez", "brigada", "brin", "brisača", "britev", 
    "brivec", "brki", "brlog", "brodolom", "brokat", "brom", "bron", "broška", 
    "brusnica", "buba", "bucika", "buča", "bučka", "budilka", "budist", 
    "budizem", "bukev", "buldog", "buldožer", "bulvar", "bumerang", "bunker", 
    "Bur", "burek", "burleska", "bušizem", "butan", "butara", "capoeira", 
    "carina", "cedra", "ceh", "celibat", "celica", "celina", "celo", "celofan", 
    "celota", "cement", "cena", "cenzura", "cepivo", "cerij", "cerkev", "Cerkev", 
    "cesar", "cesarica", "cesarstvo", "cesta", "cev", "cezar", "cezij", 
    "cianid", "cibetovka", "ciborij", "cigara", "cigareta", "ciklon", "cilj", 
    "cimet", "cink", "cinober", "Ciprčan", "cipresa", "cirilica", "cirkonij", "cirkus", "ciroza", "cirus", 
    "cisterna", "citadela", "citat", "citre", "civilizacija", "cmok", "copata", "curek", 
    "cvet", "cvetača", "čaj", "čajanka", "čaplja", "čar", "čarovnica", "čarovnik", 
    "čas", "časopis", "čast", "čebela", "čebelarstvo", "čebula", "Čeh", "ček", "čekan", 
    "čelada", "čeljust", "čeljustnica", "čelnica", "čelo", "čembalo", "česen", "češčina", 
    "češnja", "četrtek", "četrtfinale", "četrtina", "četvorka", "čevelj", "čigra", "Čilenec", 
    "činčila", "činele", "čipka", "čižek", "član", "članek", "članstvo", "členek", 
    "členica", "človečnjak", "človek", "čmrlj", "čokolada", "čoln", "čopič", "čreda", 
    "črevo", "čriček", "črka", "črnika", "črnilo", "Črnogorec", "črta", "črv", "čudež", 
    "čustvo", "čutara", "dadaizem", "dajalnik", "daktil", "dalija", "daljnogled", 
    "dalmatinec", "damjak", "dan", "Danec", "danica", "danka", "danščina", "darilo", 
    "darmštadtij", "darvinizem", "datelj", "dativ", "datum", "davek", "davica", "deblo", 
    "december", "deček", "dedič", "dediščina", "definicija", "dejanje", "dejavnost", 
    "dekan", "dekla", "dekle", "deklinacija", "del", "delavec", "delavnica", "deležnik", 
    "delfin", "delo", "delodajalec", "delta", "demografija", "demokracija", "demon", 
    "denar", "denarnica", "dendrolog", "dendrologija", "depresija", "dermatolog", 
    "desetletje", "desetletnica", "deska", "destilarna", "dete", "detektiv", "detelja", 
    "devica", "Devteronomij", "dezerter", "dež", "dežela", "dežnik", "diadem", 
    "diafragma", "diakon", "diamant", "dieta", "dihur", "dijak", "diktator", 
    "diktatura", "dim", "dimlje", "dimnik", "dinamit", "dinastija", "dingo", 
    "dinozaver", "diorama", "dirigent", "dirka", "disk", "diskriminacija", "disprozij", 
    "divizija", "divjina", "dlaka", "dlan", "dlesni", "dleto", "dnevnik", "dobrodelnost", 
    "dogodek", "dogodivščina", "dojenček", "dojilja", "dok", "dokument", "dolar", 
    "dolina", "dolmen", "določba", "dolomit", "dom", "Dominikanec", "domišljija", 
    "domoljub", "domoljubje", "domorodec", "domotožje", "doping", "dostojanstvenik", 
    "dostojanstvo", "dota", "dotik", "dovoljenje", "dož", "dracena", "draga", "dragonec", 
    "dragulj", "drama", "dramaturgija", "draž", "dražba", "drek", "dren", "drhal", "driska", "drobiž", "drobnjak", "drobtina", "drog", 
    "droga", "dromedar", "dromlja", "dron", "droplja", "drozg", "drsalec", "drsalka", "drsanje", 
    "druid", "družba", "družina", "država", "državnik", "dubnij", "duda", "dude", "duh", 
    "duhovnik", "duhovščina", "duša", "dušik", "dvig", "dvigalka", "dvižni most", "dvoboj", 
    "dvojček", "dvojina", "dvom", "dvopičje", "dvor", "dvovprega", "dvoživka", "džainist", 
    "džainizem", "džamija", "džungla", "ebenovina", "ednina", "Efežanom", "egiptolog", 
    "egiptologija", "ekipa", "ekolog", "ekologija", "ekonomija", "ekonomist", "ekosistem", 
    "ekscelenca", "Eksodus", "eksosfera", "ekstaza", "ekvator", "elektrika", "elektrolit", 
    "elektroliza", "elektron", "eliksir", "emajl", "embrij", "emigracija", "eminenca", 
    "emir", "emirat", "emu", "emulzija", "enačaj", "enačba", "enakonočje", "enciklopedija", 
    "encim", "endokrinologija", "energija", "enklava", "enoboštvo", "enodnevnica", "enolog", 
    "enota", "entomolog", "entomologija", "entropija", "ep", "epidemija", "epidemiologija", 
    "epilepsija", "epoleta", "epopeja", "epruveta", "erbij", "erekcija", "erozija", "Eskim", 
    "esperanto", "ester", "Estera", "estetika", "Estonec", "estonščina", "estuarij", "etan", 
    "eter", "etika", "etimologija", "etnograf", "etnografija", "etnolog", "etnologija", 
    "etnomuzikologija", "etruskolog", "etruskologija", "Etruščan", "evangelij", "evangelist", 
    "evharistija", "evkalipt", "evnuh", "evolucija", "evolucionist", "Evropa", "evropij", 
    "Ezekiel", "Ezra", "fagot", "fakulteta", "falzet", "fant", "fantek", "faraon", 
    "farmacija", "farmakopeja", "fasada", "fašist", "fašizem", "favna", "favorit", "fazan", 
    "februar", "fen", "feniks", "fermij", "ferščina", "fes", "festival", "fetus", 
    "fevdalizem", "fibula", "figa", "file", "Filemon", "filigran", "Filipljanom", "filister", 
    "film", "filozof", "filozofija", "filter", "finale", "Finec", "finščina", "fitopatologija", 
    "fizik", "fizika", "fiziologija", "fizioterapija", "fižol", "fjord", "flamenko", 
    "flavta", "flavtist", "fliš", "flora", "floret", "fluor", "fokstrot", "fonem", 
    "forum", "fosfat", "fosfor", "fosil", "fotograf", "fotografija", "foton", 
    "fotosinteza", "frača", "frak", "francij", "francoščina", "Francoz", "frančiškan", 
    "Frank", "frankizem", "fraza", "fregata", "frekvenca", "frigidarij", "friz", "frizer", "frizijščina", "frnikola", "fronta", 
    "fuksija", "fundamentalizem", "funt", "Furlan", "furlanščina", "futurist", "futurizem", "gadolinij", 
    "Galačanom", "galaksija", "galeb", "galenit", "galerija", "galicijščina", "galij", "galona", "galop", 
    "gama", "gameta", "gams", "garaža", "gardedama", "garje", "gasilci", "gasilec", "gavčo", "gaza", 
    "gazela", "gejzir", "gen", "generacija", "general", "genetika", "Geneza", "genij", "genitiv", "genocid", 
    "geodezija", "geograf", "geografija", "geolog", "geologija", "geometrija", "geomorfologija", "gepard", 
    "geranija", "geriater", "germanij", "geslo", "geto", "gibanje", "gibon", "giljotina", "gimnastika", 
    "ginekolog", "ginekologija", "ginko", "glagol", "glas", "glasba", "glasbenik", "glasbilo", "glasoslovje", 
    "glava", "glavač", "glavnik", "glavobol", "glavonožec", "gledalec", "gledališče", "gleženj", "glina", 
    "gliva", "globa", "globina", "globus", "glodalec", "glog", "gnajs", "gnezdo", "gnoj", "gnosticizem", 
    "gnostik", "gnu", "goba", "gobavec", "gobavost", "gobec", "gobelin", "god", "godalo", "gol", "golenica", 
    "golob", "golobica", "gomila", "gonoreja", "gora", "gorčica", "gorila", "gorivo", "gorjača", "gos", 
    "gosenica", "goslač", "gosli", "gospodar", "gospodarstvo", "gospodična", "gospodinja", "gost", "gostišče", 
    "gostitelj", "gostota", "Got", "gotika", "govedina", "govnač", "govno", "govorilnica", "govorništvo", 
    "gozd", "gozdar", "gozdarstvo", "grablje", "grad", "grafem", "grafika", "grah", "gram", "gramofon", 
    "granit", "grb", "grba", "grbavec", "grboslovje", "greben", "grebljica", "greda", "greh", "grelnik", 
    "grenivka", "grešnik", "grič", "grint", "gripa", "griva", "grizli", "griža", "Grk", "grlica", "grlo", 
    "grm", "grmada", "grob", "groblja", "grobnica", "grodnica", "grof", "grofica", "grofija", "grom", 
    "groza", "grozdičje", "grozdje", "grozljivka", "grožnja", "grščina", "gruda", "gruden", "Gruzinec", 
    "guba", "gugalnica", "gugalnik", "guma", "gumb", "gumijevka", "gvanako", "gvano", "Habakuk", 
    "habitat", "hafnij", "hagiografija", "halucinacija", "hangar", "harfa", "harfist", "haribda", "harmonij", 
    "harmonika", "harpija", "harpuna", "hasij", "hašiš", "hči", "Hebrejcem", "hebrejščina", "heksameter", 
    "helebarda", "helij", "helikopter", "hematologija", "hemoglobin", "hepatitis", "herbicid", "heretik", 
    "herezija", "hermafrodit", "hermelin", "hermenevtika", "heroin", "heteroseksualnost", "hibiskus", 
    "hidrat", "hidrogeolog", "hidrogeologija", "hidrolog", "hidrologija", "hierarhija", "hieroglif", 
    "hijacinta", "hijena", "himen", "himna", "hinavec", "hinavščina", "hinduizem", "hindujec", "hiperbola", 
    "hipermarket", "hipocenter", "hipokavst", "hipoteka", "hiša", "hitrost", "hlače", "hladilnik", "hlev", 
    "hlod", "hobotnica", "hodnik", "hodulje", "hokej", "holmij", "homoseksualec", "homoseksualnost", 
    "horizont", "hornist", "hotel", "hrana", "hrast", "hrbet", "hrbtenica", "hrbtenjača", "hrček", "hren", 
    "hrestomatija", "hrib", "hrošč", "hrt", "hrup", "hrustanec", "hruška", "hrvaščina", "Hrvat", "hudič", 
    "hudournik", "hugenot", "humor", "Hun", "husit", "huzar", "ibis", "idila", "igla", "iglavec", 
    "iglica", "iglu", "igra", "igrača", "igralec", "igrišče", "ihtiologija", "ikona", "ikonografija", 
    "ikonoklazem", "ikonologija", "ikonostas", "ikozaeder", "ilustracija", "iluzija", "ime", "imenovalnik", 
    "imigracija", "imperij", "impluvij", "imunologija", "indij", "Indijanec", "Indijec", "industrializacija", 
    "industrija", "inercija", "ingver", "injekcija", "Ink", "inkrustacija", "inkvizicija", "instrumental", 
    "intarzija", "interkolumnij", "intuicija", "invazija", "inventar", "inzulin", "ionosfera", "ipsilon", 
    "Irec", "iridij", "iris", "ironija", "irščina", "iskra", "islam", "Islandec", "islandščina", "Italijan", 
    "italijanščina", "iterbij", "itrij", "Izaija", "izbruh", "izdaja", "izdajalec", "izdelek", "izdolbina", 
    "izgovor", "izgovorjava", "izgred", "izguba", "izhod", "izjema", "izkaznica", "izložba", "izobara", 
    "izobilje", "izohipsa", "izolator", "izoterma", "izotop", "izpit", "Izraelec", "izraz", "izročilo", 
    "izum", "izumitelj", "izvidnik", "izvijač", "izvin", "izvir", "izvirnik", "izvleček", "izvor", "izziv", 
    "jablana", "jabolko", "jadro", "jagnje", "jagoda", "jajca", "jajce", "jajcevod", "jajčece", "jajčevec", 
    "jajčnik", "jak", "jama", "jamb", "jambor", "jamoslovec", "jamoslovje", "janež", "janičar", "janšizem", 
    "jantar", "januar", "Japonec", "japonščina", "jarek", "jarem", "jasa", "jaslice", "jasmin", "jasnovidec", "jaspis", "jastog", "jastreb", "jašek", "javor",
    "jazbec", "jazbečar", "ječmen", "jed", "jedilnica", "jedkanica", "jedro", "jegulja",
    "jeklo", "jelen", "jelka", "jelša", "jerebica", "Jeremija", "jermen", "jesen", 
    "jeseter", "jeti", "jetika", "jetra", "jez", "jeza", "jezdec", "jezero", "jezik", 
    "jezikoslovec", "jezikoslovje", "jezuit", "jež", "ježevec", "Job", "jod", "jodlar", 
    "Joel", "joga", "jogi", "jogurt", "jopica", "joule", "Jozue", "jubilej", "Jud", 
    "Juda", "judaizem", "judo", "judovstvo", "jug", "juha", "julij", "junak", "junij", 
    "jura", "jurček", "jušnik", "juta", "jutro", "kabala", "kabel", "kača", 
    "kadilec", "kadilo", "kadmij", "kadulja", "kafra", "kajak", "kajman", "kakadu", 
    "kakav", "kaki", "kakovost", "kaktus", "kalcij", "kalcit", "kaldarij", "kalif", 
    "kalifat", "kalifornij", "kaligrafija", "kalij", "kalin", "kalorija", "kalvinec", 
    "kameja", "kamela", "kameleon", "kamen", "kamilica", "kamin", "kamion", "kamnolom", 
    "Kanadčan", "kanalizacija", "kanjon", "kanon", "kanu", "kapa", "kapavica", "kapela", 
    "kapetan", "kapibara", "kapital", "kapitalist", "kapitalizem", "kapitel", "kapnik", 
    "kapra", "kapsula", "kapuca", "karamela", "karat", "karate", "karavana", "karbonat", 
    "kardinal", "kardiogram", "kardiologija", "kariatida", "karikatura", "karlist", 
    "karlizem", "karotin", "karta", "kartograf", "kartografija", "kartuzijan", 
    "kasarna", "kasta", "kastiljščina", "kaša", "katakombe", "katalog", "Katalonec", 
    "katalonščina", "katapult", "katedrala", "katekizem", "kateter", "kation", 
    "katoda", "katoličan", "katul", "kava", "kavarna", "kavboj", "kavelj", "kaviar", 
    "kavka", "kazalec", "kazein", "kazen", "kazuar", "kefir", "kelih", "Kelt", 
    "keltiberščina", "kemija", "kemik", "kenguru", "kenozoik", "kentaver", "kepa", 
    "keramika", "kerub", "kij", "kila", "kilogram", "kilometer", "kimavec", "kimono", 
    "kinin", "kino", "kinologija", "kip", "kipar", "kiparstvo", "kipec", "kirasir", 
    "kirij", "kirurg", "kirurgija", "kis", "kisik", "kislica", "kislina", "kit", 
    "kita", "Kitajec", "kitajščina", "kitara", "kitarist", "kivi", "kladivce", 
    "kladivo", "klan", "klarinet", "klasifikacija", "klatež", "klavir", "klementina", 
    "klepet", "klepsidra", "kleptoman", "klerikalizem", "klešče", "klet", "kletvica", 
    "klic", "klicaj", "klimaks", "klinopis", "klitoris", "ključ", "ključavnica", 
    "ključnica", "kljuka", "kljunaš", "kloaka", "klobasa", "klobčič", "klobučevina", 
    "klobuk", "klofuta", "klokan", "klon", "klop", "klopotača", "klor", "klorofil", 
    "klovn", "klub", "kmet", "kmetija", "kmetijstvo", "kneginja", "knez", "kneževina", 
    "knjiga", "knjigarna", "književnost", "knjižnica", "knjižničar", "koala", "kobalt", 
    "kobila", "kobilica", "kobra", "kocka", "koča", "kočija", "kočijaž", "kočnik", 
    "kodeks", "koder", "kofein", "kojot", "koka", "kokain", "kokos", "kokoš", 
    "kokošnjak", "koks", "kolač", "kolajna", "koledar", "koleno", "kolera", 
    "kolesarstvo", "kolibri", "količina", "količnik", "kolk", "kolo", "kolonializem", 
    "kolonija", "kolonizacija", "kolonizator", "Kološanom", "kolovrat", "komar", 
    "komat", "komatar", "kombi", "komedija", "komentator", "komet", "komisariat", 
    "komolec", "kompas", "komuna", "komunist", "komunizem", "koncert", "koncil", 
    "končnica", "kondom", "kondor", "konec", "konfucianizem", "konglomerat", 
    "kongres", "konj", "konjenica", "konjenik", "konjereja", "konjušnik", "konklave", 
    "konkubina", "konkvistador", "konservativec", "konstanta", "kontesa", 
    "kontinent", "kontrabas", "kontracepcija", "konzul", "konzulat", "kopalke", 
    "koper", "kopilot", "kopito", "kopje", "kopun", "koračnica", "koral", "korala", 
    "koran", "Korejec", "korejščina", "koren", "korenika", "korenina", "korenje", 
    "koreografija", "koriander", "Korinčanom", "kormoran", "kornet", "koromač", 
    "korteks", "koruza", "kos", "kosa", "kosilo", "kositer", "kosmulja", "kost", 
    "kostanj", "koš", "košara", "košarka", "koščica", "koštrun", "košuta", "kot", 
    "kotlina", "kovač", "kovačnik", "kovanec", "kovček", "kovina", "kovnica", 
    "koza", "kozarec", "koze", "kozel", "kozmolog", "kozmologija", "kozorog", 
    "koža", "koželjnica", "kraj", "kraja", "krajina", "kralj", "kraljestvo", 
    "kraljevina", "kraljica", "kramp", "krap", "kras", "krasoslovec", "krasoslovje", 
    "krastača", "krater", "kratica", "krava", "kravata", "krdelo", "kreda", "krema", 
    "kremen", "krempelj", "krepost", "kres", "kresnica", "kreša", "kri", "krik", "kriket", "krilo", "krinolina", "kripta", 
    "kriptograf", "kriptografija", "kriptologija", "kripton", "kristadelfijanec", "kristal", "kristalografija", 
    "kristjan", "kriterij", "krivda", "krivoverec", "kriza", "krizantema", "križ", "križanec", "križanka", 
    "križar", "križišče", "križnica", "krma", "krmilka", "krof", "krog", "krogla", "krojač", "krokar", 
    "krokodil", "krom", "kromanjonec", "krompir", "krona", "krošnja", "krst", "krsta", "krstitelj", 
    "krščanstvo", "krt", "krtača", "krtina", "kruh", "krupje", "krutost", "krvnik", "krzno", "ksenon", 
    "kuga", "kuhar", "kuhinja", "kukavica", "kumara", "kumarica", "kumina", "kuna", "kunec", "kup", 
    "kupola", "kura", "kurba", "Kurd", "kurdščina", "kurec", "kurje oko", "kustos", "kuščar", "kutina", 
    "kvadrat", "kvark", "kvas", "labod", "laboratorij", "labradorec", "ladinščina", "ladja", "laguna", 
    "lajež", "lak", "lakaj", "lakota", "lama", "lampijon", "lan", "lanolin", "lantan", "lapor", "laso", 
    "lastnik", "lastnina", "lastovica", "lasulja", "latinščina", "latrina", "lava", "lavrencij", "lazar", 
    "laž", "lažnivec", "lect", "leča", "led", "ledenik", "ledišče", "ledvica", "legenda", "legvan", 
    "lehnjak", "lek", "lekarna", "leksikologija", "lenivec", "leopard", "lepilo", "lepopis", "lepota", 
    "les", "leska", "lesorez", "lestev", "lešnik", "let", "letališče", "letalo", "leto", "Letonec", 
    "letonščina", "lev", "levinja", "Levitik", "levkemija", "lezbijka", "liana", "Libanonec", "liberalizem", 
    "lice", "ličinka", "ličje", "ličnica", "liga", "ligenj", "lik", "likalnik", "liker", "lilija", 
    "limfa", "limona", "limonada", "lingvist", "lingvistika", "lipa", "lira", "lisica", "lisička", "list", 
    "listopad", "lišaj", "liter", "literatura", "litij", "litografija", "litosfera", "litota", "Litovec", 
    "liturgija", "litvanščina", "lizena", "lizika", "ljubezen", "ljubosumnost", "ljudstvo", "lobanja", 
    "ločilo", "ločina", "logaritem", "logika", "lok", "lokativ", "lokomotiva", "lokvanj", "lom", "lončar", 
    "lončenina", "lonec", "lopar", "lopata", "lopatica", "los", "losos", "lotos", "lov", "lovec", 
    "lovor", "lubenica", "lubje", "luč", "luknja", "luna", "luska", "luštrk", "lutecij", "luteranec", 
    "lutka", "lutkar", "luža", "macesen", "macola", "mačeha", "mačka", "madež", "Madžar", 
    "madžarščina", "magma", "magnet", "magnezij", "magnolija", "mah", "mahagoni", "maj", "majaron", 
    "majnica", "majoneza", "majordom", "majtnerij", "mak", "Makedonec", "makedonščina", "maketa", "Malahija", 
    "malarija", "malica", "malina", "malteščina", "Maltežan", "mambo", "mamilo", "mamut", "mandarina", 
    "mandelj", "mandljevec", "mandolina", "mangan", "manifest", "manšeta", "manufaktura", "maraton", 
    "marcipan", "marec", "marelica", "margarina", "marihuana", "marioneta", "marjetica", "marka", 
    "markiz", "marksist", "marksizem", "marmelada", "marmor", "masa", "maska", "maslo", "mast", 
    "mastif", "maša", "matematika", "materija", "materinščina", "maternica", "mati", "matriarhat", 
    "mavec", "mavrica", "mavzolej", "mazilo", "mazohist", "mazurka", "meander", "meč", "meča", "mečarica", 
    "med", "medalja", "medenica", "medenina", "medica", "medicina", "meditacija", "medmet", "meduza", 
    "medved", "medvedka", "megalit", "megaron", "megla", "mehanika", "mehkužec", "mehur", "meja", 
    "mejoza", "melancana", "melisa", "melona", "mena", "menarha", "mendelevij", "menih", "menišček", 
    "meništvo", "menopavza", "menstruacija", "menza", "mera", "merilo", "merjasec", "mesec", "mesečina", 
    "mesečnik", "mesnica", "meso", "mestnik", "mesto", "met", "meta", "metafizika", "metafora", "metalurg", 
    "metalurgija", "metamorfoza", "metan", "meteor", "meteorit", "meteorolog", "meteorologija", "meter", 
    "metla", "metonimija", "metopa", "metro", "metulj", "metuljček", "mezeg", "mezinec", "mezosfera", 
    "mezozoik", "mezzosopran", "Mihej", "mihrab", "mikologija", "mikrobiolog", "mikrobiologija", 
    "mikrokozmos", "mikroskop", "milijarda", "milijon", "milja", "miljnik", "milo", "miloba", "mimikrija", 
    "mina", "minaret", "mineralogija", "miniatura", "miniaturist", "minister", "minuta", "mir", "mira", 
    "mirabela", "mirta", "misel", "misijonar", "misterij", "miš", "mišelovka", "mišica", "miška", 
    "mit", "mitologija", "mitoza", "mitraljez", "miza", "mizar", "mladika", "mlaka", "mleko", "mlin",
    "mlinar", "mnogoboštvo", "množina", "moč", "moča", 'močerad', 'močvirje', 'močvirnik', 'moda', 'model',
    'modem', 'modernizem', 'modrc', 'modrica', 'modrina', 'modrost', 'mojstrovina', 'moka', 'moldavščina',
    'molekula', 'molibden', 'molilnica', 'molitev', 'molivec', 'molj', 'moment', 'monarh', 'monarhija', 'monarhist',
    'mongol', 'mongolščina', 'monizem', 'monogamija', 'monokel', 'monoteizem', 'monsun', 'monštranca',
    'mora', 'moratorij', 'morena', 'morfem', 'morfologija', 'morilec', 'morje', 'mormon', 'mornar',
    'mornarica', 'most', 'mošeja', 'moški', 'moštvo', 'mošus', 'motel', 'motika', 'motiv', 'motnja',
    'motor', 'mozaik', 'mozeg', 'mozolj', 'mož', 'možgani', 'možnar', 'možnost', 'mrak', 'mravlja',
    'mravljinčar', 'mravljišče', 'mrena', 'mrest', 'mreža', 'mrežnica', 'mrhovina', 'mrk', 'mrož',
    'mrtvaški prt', 'mrtvašnica', 'mrtvica', 'mučenec', 'mučeništvo', 'muezin', 'muflon', 'muha', 'mula',
    'mulat', 'mulj', 'mumija', 'mumps', 'mungo', 'muren', 'murva', 'musliman', 'muslin', 'muškat', 'mušketa',
    'mušketir', 'mušnica', 'muza', 'muzej', 'muzeologija', 'muzikologija', 'naboj', 'nacionalist', 'nacist',
    'nacizem', 'nadangel', 'nadlahtnica', 'nadlaket', 'nadrealist', 'nadrealizem', 'nadškof', 'nafta', 'naftalin',
    'nagelj', 'naglas', 'nagrada', 'nahrbtnik', 'Nahum', 'najdišče', 'najemnik', 'najemnina', 'naključje', 'nakovalce',
    'namen', 'napad', 'napadalec', 'napaka', 'napis', 'napoj', 'naramnice', 'narava', 'narcisa', 'narečje', 'narkoman',
    'narod', 'nart', 'narteks', 'nasilje', 'naslov', 'natakar', 'natrij', 'navada', 'navijač', 'nebesa', 'nebo',
    'nedelja', 'nedoločnik', 'Nehemija', 'nektar', 'Nemec', 'nemščina', 'neodim', 'neolitik', 'neon', 'nepalščina',
    'neptunij', 'neskončnost', 'nesreča', 'nešplja', 'netopir', 'Nevenka', 'nevihta', 'nevroza', 'nevtron', 'nihalo',
    'nihanje', 'nikelj', 'nimfa', 'niobij', 'niša', 'nit', 'nitrat', 'Nizozemec', 'nizozemščina', 'njiva', 'nobelij',
    'noč', 'noga', 'nogavica', 'nogomet', 'nogometaš', 'noht', 'noj', 'nominativ', 'norec', 'norice', 'norišnica',
    'norost', 'norveščina', 'Norvežan', 'nos', 'nosečnost', 'nosnica', 'nosorog', 'nostrifikacija', 'november', 'novinar',
    'novinarstvo', 'novofundlandec', 'nož', 'nožnica', 'Numeri', 'nuna', 'nutrija', 'oaza', 'obad', 'obala', 'občestvo',
    'obelisk', 'obisk', 'obiskovalec', 'objem', 'oblak', 'obleka', 'obletnica', 'oblika', 'obliv', 'obliž', 'obljuba',
    'oboa', 'obok', 'obrat', 'obraz', 'obred', 'obrezovanje', 'obroč', 'obrok', 'obrv', 'obsedenost', 'obseg',
    'observatorij', 'obup', 'ocean', 'oceanograf', 'očala', 'oče', 'očim', 'oda', 'odboj', 'odbojka', 'odeja', 'oder',
    'oderuštvo', 'odgovor', 'odhod', 'odkritje', 'odkupnina', 'odlitek', 'odnos', 'odpadnik', 'odplaka', 'odpor', 'odprava',
    'odprtina', 'odrgnina', 'odsev', 'odtenek', 'ogenj', 'oglas', 'ogledalo', 'oglje', 'ogljik', 'ognjemet', 'ognjenik',
    'ognjišče', 'ograja', 'ogrlica', 'ohm', 'ohrovt', 'okapi', 'okarina', 'okcitanščina', 'okel', 'oklep', 'oklepaj',
    'okno', 'oko', 'okoliščina', 'okolje', 'okop', 'okostje', 'okra', 'oksid', 'oksimoron', 'oktava', 'oktober', 'okulist',
    'okus', 'okužba', 'okvir', 'olajšanje', 'oligarhija', 'oliva', 'olje', 'oljenka', 'oljka', 'oltar', 'omaka', 'omara',
    'omega', 'omela', 'omikron', 'omleta', 'omotica', 'oniks', 'onkolog', 'onkologija', 'onomastika', 'opal', 'opat',
    'opatija', 'opatinja', 'opeka', 'opeklina', 'opera', 'operacija', 'opereta', 'opica', 'opij', 'opis', 'oploditev',
    'opna', 'opomba', 'opora', 'oporoka', 'oposum', 'oprašitev', 'oproda', 'optik', 'optika', 'opuncija', 'opuščaj',
    'orakelj', 'oralni seks', 'orangutan', 'oranžerija', 'orbita', 'oreh', 'orel', 'organ', 'organizacija', 'organizem',
    'orgazem', 'orgle', 'orglice', 'orhideja', 'origano', 'oriks', 'oris', 'orjak', 'orkan', 'orlica', 'orlič', 'ornitolog',
    'ornitologija', 'orodnik', 'orogeneza', 'os', 'osa', 'osamelec', 'osat', 'osciloskop', 'oseba', 'osebek', 'osebnost',
    'oseka', 'osel', 'oskoruš', 'osla', 'osmerokotnik', 'osmij', 'osmoza', 'osnova', 'osončje', 'ostriga', 'ostrivec', 'ostroa',
    'ošpice', 'oteklina', 'otok', 'otorinolaringolog', 'otrok', 'otroštvo', 'ovca', 'ovčar', 'oven', 'oves', 'ovira', 'ovratnik',
    'ozadje', 'Ozej', 'ozemlje', 'oznanjenje', 'ozračje', 'ozvezdje', 'ožina', 'padalec', 'padalo', 'padavica', 'padec',
    'pahljača', 'pajčevina', 'pajčolan', 'pajek', 'pajkovec', 'palača', 'palačinka', 'paladij', 'palčnik', 'palec',
    'paleobotanika', 'paleografija', 'paleolitik', 'paleontolog', 'paleontologija', 'paleozoik', 'paleta', 'palica',
    'palimpsest', 'palindrom', 'palisada', 'palma', 'pamflet', 'pampa', 'pan', 'panda', 'pandemija', 'panj', 'pankrt',
    'panorama', 'panteizem', 'papež', 'papiga', 'papir', 'papirus', 'paprika', 'par', 'para', 'parabola', 'paradižnik',
    'paralelogram', 'parfum', 'park', 'parket', 'parlament', 'parni stroj', 'parnik', 'partizan', 'pas', 'pasavec', 'pasijonka',
    'paskal', 'pasma', 'past', 'pastir', 'pastirica', 'patent', 'patina', 'patolog', 'patologija', 'patriarh', 'patriarhat',
    'patricij', 'pav', 'pavijan', 'pazduha', 'peč', 'pečat', 'peder', 'pediater', 'pediatrija', 'pega', 'pegatka', 'pehtran', 'pek', 'peka', 'pekarna', 'pekel', 'pelargonija', 'pelikan', 'pelin', 'pelod', 'pena', 'penica', 'penis', 'pentameter', 'pepel', 'pepelika', 'pepelnik', 'pergament', 'periskop', 'perjanica', 'pero', 'peron', 'personal', 'perspektiva', 'Peruanec', 'perut', 'perzijščina', 'pes', 'pesa', 'pesek', 'pesem', 'pesjak', 'peskovnik', 'pesmarica', 'pesnik', 'pesnitev', 'pest', 'pesticid', 'pestič', 'pestunja', 'peščenjak', 'peška', 'peta', 'petek', 'petelin', 'peterokotnik', 'peteršilj', 'peticija', 'petorček', 'petunija', 'pevec', 'pianist', 'pica', 'pihalo', 'pijača', 'pijanec', 'pijavka', 'pik', 'pika', 'pikapolonica', 'pikolo', 'pila', 'pilaster', 'pilot', 'pilula', 'pinceta', 'pingvin', 'pipa', 'pipeta', 'piramida', 'pire', 'piroman', 'pirueta', 'pisarna', 'pisatelj', 'pisava', 'pismenost', 'pismo', 'pistacija', 'piščal', 'piščanec', 'piškot', 'pištola', 'pita', 'piton', 'pivo', 'pivovarna', 'pižama', 'placenta', 'plača', 'pladenj', 'plakat', 'plamen', 'plamenec', 'planet', 'planika', 'planota', 'plast', 'plastika', 'plastnica', 'plašč', 'plat', 'platana', 'platina', 'platno', 'plavanje', 'plavček', 'plavica', 'plavut', 'plaz', 'plazilec', 'plaža', 'plebejec', 'pleme', 'plemstvo', 'plen', 'pleonazem', 'ples', 'plesalec', 'plevel', 'plima', 'plin', 'pliš', 'pljuča', 'pljučnica', 'pljunek', 'pločevinka', 'pločnik', 'plod', 'ploskev', 'plošča', 'ploščina', 'plovba', 'plovilo', 'plug', 'plundra', 'pluta', 'plutonij', 'pobarvanka', 'pod', 'podboj', 'podcelina', 'podgana', 'podhranjenost', 'podkev', 'podlahtnica', 'podlaket', 'podlasica', 'podložnik', 'podmornica', 'podnaslov', 'podnebje', 'podoba', 'podočnik', 'podpičje', 'podpis', 'podplat', 'podpora', 'podstrešje', 'podzemlje', 'pogačica', 'pogan', 'poganstvo', 'poglavar', 'poglavje', 'pogodba', 'pogovor', 'pogreb', 'pogum', 'pohištvo', 'pojav', 'pok', 'pokal', 'poker', 'poklon', 'pokoj', 'pokol', 'pokop', 'pokopališče', 'pokrov', 'pokrovka', 'pol', 'polarizacija', 'polbog', 'poldan', 'poldnevnik', 'polenovka', 'polet', 'poletje', 'polfinale', 'polh', 'polica', 'policaj', 'policijska ura', 'poligamija', 'polihimnija', 'polip', 'politeizem', 'politik', 'politika', 'Poljak', 'Poljakinja', 'polje', 'poljedelstvo', 'poljščina', 'poljub', 'poljubljanje', 'polk', 'polka', 'polmer', 'polnoč', 'polobla', 'poloneza', 'polonij', 'polotok', 'polovica', 'poltema', 'polž', 'pomada', 'pomanjkanje', 'pomaranča', 'pomen', 'pomenoslovje', 'pomislek', 'pomlad', 'pomoč', 'pomol', 'pomorščak', 'pomota', 'pončo', 'ponedeljek', 'ponev', 'poni', 'ponirek', 'ponos', 'popek', 'poper', 'popkovnica', 'poplava', 'popotnik', 'por', 'pora', 'poraz', 'porcelan', 'porfir', 'pornografija', 'poročnik', 'porod', 'porodničar', 'poroka', 'porota', 'portal', 'portret', 'Portugalec', 'portugalščina', 'posadka', 'posilstvo', 'poskus', 'poslanec', 'posledica', 'poslovnež', 'posneto mleko', 'posojilo', 'pospešek', 'post', 'postaja', 'postelja', 'posteljica', 'postovka', 'postrv', 'pošast', 'poškodba', 'pošta', 'poštar', 'pot', 'potapljač', 'potepuh', 'potnik', 'potok', 'potomec', 'potomstvo', 'potovanje', 'potres', 'potrpežljivost', 'povedek', 'povod', 'povodec', 'povoj', 'povratnik', 'površina', 'pozavna', 'pozavnist', 'pozitron', 'pozornost', 'požar', 'požiralnik', 'prag', 'pragozd', 'prah', 'pralni stroj', 'praprot', 'prašek', 'prašič', 'prašnik', 'praštevilo', 'pravica', 'pravljica', 'pravnuk', 'pravoslavec', 'prazeodim', 'prazgodovina', 'praznik', 'pražival', 'prebivalec', 'prebivalstvo', 'preddverje', 'predica', 'predlog', 'predmet', 'prednik', 'prednost', 'predpekel', 'predsednik', 'predsodek', 'pregovor', 'Pregovori', 'pregreha', 'prehlad', 'preja', 'preklada', 'prekletstvo', 'premer', 'premikalka', 'premirje', 'premog', 'premogovnik', 'prenajedanje', 'prepelica', 'prepoved', 'preproga', 'prepustnica', 'prerija', 'prerok', 'prerokba', 'presenečenje', 'presta', 'prestava', 'prestol', 'prestolnica', 'prestolonaslednik', 'preteklost', 'pretor', 'prevajalec', 'prevara', 'prevod', 'prevodnik', 'prezbiterij', 'preživnina', 'prha', 'prhljaj', 'priba', 'pridevnik', 'pridiga', 'pridigar', 'prihod', 'prihodnost', 'priimek', 'prijatelj', 'prijateljica', 'prijateljstvo', 'prilastek', 'priležnica', 'priložnost', 'primer', 'primera', 'princ', 'princesa', 'pripadnik', 'pripona', 'pripoved', 'priroda', 'prisega', 'prisilni jopič', 'prislov', 'prispevek', 'prispodoba', 'pristan', 'pristanek', 'pristanišče', 'prišlek', 'pritisk', 'privid', 'prizma', 'prizor', 'prižnica', 'producent', 'profesor', 'prometij', 'propaganda', 'propan', 'propeler', 'propileje', 'prosinec', 'proso', 'prostata', 'prostitutka', 'prostornina', 'prostozidar', 'protaktinij', 'protein', 'protestant', 'protipapež', 'protipomenka', 'protireformacija', 'protislovje', 'proton', 'provansalščina', 'provinca', 'prsi', 'prsni koš', 'prst', 'prstan', 'prstanec', 'pršica', 'pršut', 'prt', 'prtiček', 'prtljaga', 'prtljažnik', 'pručka', 'prvak', 'prvenstvo', 'psalm', 'Psalmi', 'psalterij', 'psevdonim', 'psica', 'psihiater', 'psihiatrija', 'psihoanaliza', 'psiholog', 'psihologija', 'psihopat', 'psovka', 'pšenica', 'ptica', 'ptič', 'ptičje strašilo', 'puberteta', 'puma', 'punčica', 'punk', 'pupek', 'puran', 'puščava', 'puščavnik', 'puščica', 'puška', 'putto', 'raba', 'rabarbara', 'raca', 'racak', 'racija', 'računalnik', 'računstvo', 'radar', 'raderfordij', 'radij', 'radio', 'radirka', 'radon', 'radost', 'radovednost', 'radža', 'raj', 'rak', 'raketa', 'rakun', 'rama', 'ran', 'rana', 'rapir', 'rapsodija', 'rasa', 'rasist', 'rasizem', 'rast', 'rastlina', 'rastlinojedec', 'rastlinstvo', 'ravan', 'ravnatelj', 'ravnik', 'ravnilo', 'ravnina', 'ravnotežje', 'razgled', 'razglednica', 'razlika', 'razlog', 'razmerje', 'razmnoževanje', 'razodetje', 'razpelo', 'razpoka', 'razpon', 'razred', 'razstava', 'raztopina', 'razvoj', 'rdečke', 'rebro', 'red', 'redkev', 'redkost', 'refektorij', 'referendum', 'reformacija', 'refugij', 'rega', 'regrat', 'reinkarnacija', 'reka', 'reklo', 'rekviem', 'relativnost', 'relief', 'religija', 'relikvija', 'renij', 'rep', 'repa', 'repatica', 'represija', 'republika', 'republikanec', 'republikanizem', 'resa', 'resnica', 'resonanca', 'restavracija', 'rešetka', 'rešitev', 'retorika', 'retoromanščina', 'retorta', 'revija', 'revma', 'revolucija', 'revolveraš', 'revščina', 'rezbar', 'rezidenca', 'rezilo', 'režim', 'režiser', 'riba', 'ribežen', 'ribič', 'ribnik', 'rikša', 'rilec', 'rima', 'Rimljani', 'ring', 'ringlo', 'ris', 'risba', 'rit', 'ritem', 'ritnik', 'riž', 'rjuha', 'rob', 'robec', 'robidnica', 'robot', 'rock', 'rodij', 'rodilnik', 'rododendron', 'rodoslovec', 'rodoslovje', 'rodovnik', 'roentgenij', 'rog', 'roj', 'rojstvo', 'roka', 'rokav', 'rokavica', 'rokoborba', 'rokoborec', 'rokomet', 'rokometaš', 'rokopis', 'roman', 'romanje', 'romanopisec', 'romanticizem', 'romar', 'romb', 'Romun', 'romunščina', 'rop', 'ropar', 'rosa', 'rovka', 'roza', 'rozina', 'roža', 'roženica', 'roževina', 'rožmarin', 'rožni venec', 'rožnik', 'rt', 'rubidij', 'rubin', 'ruda', 'rudar', 'rudarstvo', 'rudnik', 'rudnina', 'ruj', 'rum', 'rumba', 'rumenjak', 'runa', 'runo', 'rupija', 'Rus', 'ruščina', 'ruševec', 'Ruta', 'rutenij', 'rutica', 'rž', 'sablja', 'sabotaža', 'sadež', 'sadje', 'sadovnjak', 'safari', 'saksofon', 'saksofonist', 'salama', 'salsa', 'samarij', 'samba', 'samoglasnik', 'samokolnica', 'samomor', 'samorog', 'samostalnik', 'samostan', 'samozadovoljevanje', 'sandalovina', 'sanskrt', 'sapica', 'sapnik', 'sardela', 'sardina', 'sarkazem', 'sarkofag', 'satelit', 'saten', 'satir', 'satira', 'savana', 'scenarij', 'scenarist', 'sečevod', 'sedlo', 'sef', 'seizmograf', 'seizmolog', 'seizmologija', 'sejem', 'sekira', 'seks', 'sekunda', 'sekvoja', 'selen', 'semafor', 'semantika', 'seme', 'semenčica', 'semenovod', 'senator', 'senca', 'senčnica', 'sendvič', 'seno', 'september', 'seraf', 'serenada', 'sesalec', 'sestra', 'sestrična', 'seter', 'sever', 'sezam', 'seznam', 'shizma', 'shramba', 'siborgij', 'sidrišče', 'sidro', 'sila', 'silicij', 'simbioza', 'simbol', 'simbolizem', 'sin', 'sinagoga', 'sindikat', 'sinica', 'sinkopa', 'sinkretizem', 'sipa', 'sir', 'Sirec', 'siromak', 'sirotka', 'sirup', 'sito', 'sivka', 'skala', 'skandij', 'skat', 'skavt', 'skladatelj', 'skladnja', 'sklanjatev', 'skleda', 'sklep', 'sklepnik', 'sklon', 'sklopka', 'skobec', 'skodelica', 'skorbut', 'skorja', 'skrilavec', 'skrinja', 'skrivnost', 'skupina', 'skupnost', 'skuša', 'skuta', 'slad', 'sladkarija', 'sladkor', 'sladoled', 'slak', 'slalom', 'slama', 'slamnik', 'slanica', 'slanik', 'slanina', 'slanost', 'slap', 'slaščičar', 'slavec', 'slavolok', 'slepič', 'slez', 'slezenovec', 'slika', 'slikanica', 'slikar', 'slikarstvo', 'slina', 'sliva', 'slivovka', 'sloga', 'slon', 'slonica', 'slonovina', 'slop', 'Slovak', 'slovar', 'slovaščina', 'Slovenec', 'slovenščina', 'sloves', 'slovnica', 'slušalka', 'služabnik', 'smaragd', 'smetana', 'smodnik', 'smokva', 'smola', 'smrad', 'smrdokavra', 'smreka', 'smrt', 'smučanje', 'smučka', 'smuk', 'smukec', 'snaha', 'sneg', 'snežak', 'snežinka', 'snob', 'snov', 'soba', 'sobarica', 'sobolj', 'sobota', 'socialist', 'socializem', 'sociolingvistika', 'sociolog', 'sociologija', 'sočutje', 'sod', 'sodnik', 'Sodniki', 'sodomija', 'Sofonija', 'soglasnik', 'soja', 'sok', 'sokol', 'sol', 'solata', 'soliter', 'solnica', 'solza', 'solzivec', 'som', 'sonce', 'sončnica', 'sonda', 'sonet', 'sopomenka', 'sopran', 'sopranistka', 'soprog', 'sorodnik', 'sosed', 'sošolec', 'soteska', 'sotočje', 'sova', 'sovhoz', 'sovraštvo', 'sovražnik', 'spalnica', 'spanje', 'spekter', 'speleolog', 'speleologija', 'sperma', 'spermij', 'spis', 'splav', 'spočetje', 'spodnjice', 'spojina', 'spol', 'spolno občevanje', 'spolovilo', 'spomenik', 'spomin', 'spominčica', 'spondej', 'sponka', 'spora', 'sporočilo', 'spoštovanje', 'spoved', 'spregatev', 'sprememba', 'spremenljivka', 'spretnost', 'sprevod', 'sprevodnik', 'spužva', 'srajca', 'sraka', 'srakoper', 'sramota', 'sranje', 'Srb', 'srbščina', 'srce', 'srd', 'srebrar', 'srebrnina', 'srebro', 'sreča', 'sreda', 'sredina', 'sredinec', 'središče', 'srh', 'srobot', 'srp', 'sršen', 'stadij', 'stadion', 'staja', 'stajica', 'stanca', 'stanje', 'stanovanje', 'stara mati', 'stari oče', 'starinar', 'starši', 'statist', 'statistika', 'stativ', 'stavba', 'stavek', 'stavka', 'stavkokaz', 'stažist', 'steber', 'steblo', 'steklenica', 'steklina', 'steklo', 'stela', 'stelja', 'stena', 'stenica', 'stenj', 'step', 'stepa', 'stereobat', 'sterilizacija', 'steza', 'stikalo', 'stilobat', 'stoa', 'stojnica', 'stol', 'stoletje', 'stoletnica', 'stolnica', 'stolp', 'stolpec', 'stonoga', 'stopalo', 'stopica', 'stopnišče', 'stopnja', 'storž', 'stožec', 'strah', 'strahopetec', 'strahopetnež', 'strahopetnost', 'strakoš', 'stran', 'stranišče', 'stranka', 'strast', 'strategija', 'stratigrafija', 'stratosfera', 'stratus', 'strd', 'streha', 'strel', 'strela', 'strelec', 'strelovod', 'streme', 'stremence', 'strežnik', 'stric', 'strigalica', 'strnad', 'stroj', 'strojnica', 'stroncij', 'strop', 'strpnost', 'struna', 'strup', 'stržek', 'studenec', 'studio', 'stvar', 'stvaritev', 'stvarjenje', 'stvarstvo', 'sublimacija', 'sulfat', 'sulica', 'sultan', 'sultanat', 'sum', 'supermarket', 'supernova', 'suša', 'sušec', 'sušica', 'suženj', 'suženjstvo', 'svahili', 'svak', 'svakinja', 'svastika', 'svat', 'sveča', 'svečan', 'svečka', 'sveder', 'svet', 'svetilka', 'svetilnik', 'svetišče', 'svetloba', 'svetlobnica', 'svetnik', 'svetovljan', 'sveženj', 'svila', 'sviloprejka', 'svinčnica', 'svinčnik', 'svinec', 'svinja', 'svinjak', 'svinjina', 'svizec', 'svoboda', 'šah', 'šahovnica', 'šakal', 'šal', 'šala', 'šaman', 'šamanizem', 'šampinjon', 'šampon', 'šarenica', 'šaš', 'ščavje', 'ščegetavček', 'ščinkavec', 'ščit', 'ščurek', 'šega', 'šen', 'šerif', 'šestilo', 'šilček', 'šimpanz', 'šintoist', 'šintoizem', 'šipek', 'širina', 'šiška', 'šiv', 'škarje', 'škatla', 'škof', 'školjka', 'škorec', 'škorenj', 'škorpijon', 'Škot', 'škrat', 'škrge', 'škripec', 'škrjanec', 'škrlatinka', 'škrob', 'škržat', 'šmarnica', 'šnavcer', 'šoja', 'šok', 'šola', 'šopek', 'šotor', 'špalir', 'Španec', 'španščina', 'špargelj', 'šport', 'športnik', 'številčnica', 'število', 'števnik', 'štipendija', 'štoparica', 'štor', 'štorklja', 'štrcelj', 'šunka', 'Šved', 'švedščina', 'Švicar', 'tableta', 'tabor', 'taca', 'tajnik', 'taksonomija', 'takt', 'taktika', 'talec', 'talij', 'talisman', 'tališče', 'talmud', 'tamburica', 'tamburin', 'tango', 'tank', 'tantal', 'taoizem', 'tapir', 'tapiserija', 'tarantela', 'tarča', 'tast', 'tašča', 'taščica', 'tat', 'Tatar', 'tatvina', 'tečaj', 'teden', 'tehnecij', 'tehnik', 'tehnologija', 'tehtnica', 'tein', 'tek', 'tekma', 'tekmovanje', 'tektonika', 'tele', 'telefon', 'teleskop', 'teletina', 'televizija', 'telo', 'teloh', 'telovnik', 'tema', 'temelj', 'tempelj', 'temperatura', 'tenis', 'tenor', 'teologija', 'teorija', 'tepidarij', 'terapija', 'terarij', 'terasa', 'terbij', 'terier', 'terilnik', 'teritorij', 'terme', 'termit', 'termodinamika', 'termosfera', 'termostat', 'teror', 'terorist', 'terorizem', 'terpentin', 'terpsihora', 'Tesaloničanom', 'tesar', 'testisi', 'testo', 'teta', 'tetanus', 'tetida', 'tetrarh', 'teža', 'težava', 'težnost', 'tiara', 'tibetanščina', 'tifus', 'tiger', 'tihožitje', 'tik', 'tilnik', 'timijan', 'timpanon', 'tipalka', 'tipka', 'tiran', 'tiranija', 'tisa', 'tiskarna', 'tisočletje', 'tisočletnica', 'tišina', 'Tit', 'titan', 'tjulenj', 'tkanina', 'tkivo', 'tla', 'tlačenka', 'tlak', 'tobak', 'tobogan', 'toča', 'točo', 'toga', 'tok', 'tolkalo', 'tolmač', 'tomahavk', 'tona', 'tonalit', 'top', 'topaz', 'toplina', 'toplota', 'topništvo', 'topograf', 'topografija', 'topol', 'toponim', 'torba', 'torek', 'torij', 'tornado', 'torpedo', 'torzija', 'torzo', 'totem', 'totemizem', 'tovariš', 'tovarna', 'tovornjak', 'tožilnik', 'tragedija', 'tragikomedija', 'traktor', 'trakulja', 'tram', 'transformator', 'trava', 'travnik', 'trdnjava', 'trebuh', 'trener', 'trenje', 'trenutek', 'trepalnica', 'trepetlika', 'trg', 'trgovec', 'trgovina', 'triangel', 'trias', 'triceps', 'trikotnik', 'trilobit', 'trilogija', 'trinog', 'trizob', 'trn', 'trnek', 'trobelika', 'trobenta', 'trobentica', 'trobilo', 'troblja', 'trofeja', 'trohej', 'trojček', 'trombocit', 'trompa', 'troposfera', 'tros', 'trot', 'trpljenje', 'trs', 'trska', 'trta', 'trtica', 'trubadur', 'trup', 'truplo', 'tsunami', 'tuberkuloza', 'tuf', 'tujec', 'tukan', 'tulij', 'tulipan', 'tuljava', 'tundra', 'tunika', 'tur', 'turban', 'Turek', 'turist', 'turizem', 'turkiz', 'turščina', 'ubežnik', 'učenec', 'učitelj', 'udarec', 'uganka', 'uhan', 'uhelj', 'uho', 'ujeda', 'ujetnik', 'Ukrajinec', 'ukrajinščina', 'ulica', 'ulomek', 'umazanija', 'umetnik', 'umetnost', 'umor', 'unča', 'uniforma', 'univerza', 'ununbij', 'ununheksij', 'ununkvadij', 'ununpentij', 'ununseptij', 'ununtrij', 'up', 'upanje', 'upor', 'uporabnik', 'ura', 'uradnik', 'uran', 'Uran', 'urbanist', 'urednik', 'urin', 'urok', 'urolog', 'uslužbenec', 'usmiljenje', 'usnje', 'usoda', 'uspavalo', 'uspeh', 'usta', 'ustanova', 'ustava', 'ustje', 'ustnica', 'ustreznica', 'uš', 'utež', 'utrdba', 'vaba', 'vadi', 'vagina', 'vajenec', 'val', 'valček', 'Valižan', 'valj', 'vampi', 'vampir', 'vanadij', 'Vandal', 'vanilija', 'varilec', 'varščina', 'varuška', 'vas', 'vaščan', 'vat', 'vaterpolo', 'vaza', 'vazektomija', 'vdova', 'vdovec', 'večer', 'večerja', 'večernica', 'večnost', 'vedro', 'vegetarijanec', 'vegetarijanka', 'veja', 'vejica', 'veka', 'vektor', 'velblod', 'veleblagovnica', 'veleposlanik', 'veleposlaništvo', 'veleslalom', 'velika sinica', 'velikan', 'veliki srpan', 'veliki traven', 'velikost', 'venec', 'Venera', 'venerolog', 'vera', 'veriga', 'veselje', 'veseloigra', 'veslo', 'vesolje', 'vest', 'veter', 'veterina', 'veterinar', 'veverica', 'vez', 'vezaj', 'vezalka', 'vezenina', 'vezir', 'veznik', 'vhod', 'viadukt', 'vice', 'vidra', 'vietnamščina', 'vihar', 'vijak', 'vijolica', 'vila', 'vilice', 'viličenje', 'vino', 'vinograd', 'vinotok', 'viola', 'violina', 'violinist', 'violončelist', 'violončelo', 'vir', 'virus', 'viski', 'višina', 'višnja', 'vitamin', 'vitez', 'vivarij', 'Vizigot', 'vizum', 'vlada', 'vladar', 'vladavina', 'vlak', 'vlakno', 'vlečka', 'vljudnost', 'vnebovzetje', 'vnuk', 'vnukinja', 'voda', 'vodič', 'vodik', 'vodja', 'vodnjak', 'vodomec', 'vogal', 'vohun', 'vojak', 'vojašnica', 'vojna', 'vojska', 'vojščak', 'vojvoda', 'vojvodina', 'vojvodinja', 'vol', 'volan', 'Volar', 'volfram', 'volk', 'volkodlak', 'volna', 'volt', 'voluhar', 'voluta', 'vombat', 'vonj', 'vosek', 'voz', 'vozel', 'vozilo', 'voznik', 'vpis', 'vprašaj', 'vprašanje', 'vrabec', 'vračalka', 'vran', 'vrana', 'vranica', 'vrat', 'vrata', 'vratar', 'vraža', 'vrba', 'vrč', 'vreča', 'vrečar', 'vreme', 'vretence', 'vretenčar', 'vreteno', 'vrh', 'vroče', 'vročina', 'vrsta', 'vrt', 'vrtača', 'vrtnar', 'vrtnica', 'vrv', 'vrzel', 'vsiljivec', 'vtič', 'vtičnica', 'vtikač', 'vtis', 'vulkan', 'vzgon', 'vzhod', 'vzklik', 'vzvod', 'vžigalica', 'začimba', 'zadnjik', 'Zaharija', 'zahod', 'zaimek', 'zajec', 'zajedalec', 'zajedalstvo', 'zajemalka', 'zajklja', 'zajtrk', 'zaklopka', 'zakon', 'zakristija', 'zaliv', 'založba', 'založnik', 'zamahniti', 'zamaknjenost', 'zamašek', 'zanamec', 'zapestje', 'zapestnica', 'zapor', 'zapredek', 'zarodek', 'zastava', 'zatilnica', 'zavarovanje', 'zavesa', 'zavest', 'zaveznik', 'zavora', 'zbirka', 'zbor', 'zdravilo', 'zdravje', 'zdravnik', 'zebra', 'zebu', 'zel', 'zelena', 'zelena žolna', 'zelenjava', 'zelišče', 'zelje', 'zemlja', 'Zemlja', 'zemljepis', 'zemljevid', 'zenica', 'zgodba', 'zgodovina', 'zgodovinar', 'zgoščenka', 'zgradba', 'zibelka', 'zid', 'zima', 'zimzelen', 'zlatar', 'zlati rez', 'zlatica', 'zlato', 'zlitina', 'zlo', 'zločin', 'zločinec', 'zlog', 'zlom', 'zmaga', 'zmagovalec', 'zmaj', 'zmeda', 'značaj', 'znak', 'znamka', 'znanje', 'znanost', 'znanstvenik', 'znoj', 'zob', 'zobobol', 'Zobotrebec', 'zobozdravnik', 'zoolog', 'zoologija', 'zrak', 'zrezek', 'zrklo', 'zvestoba', 'zvezda', 'zvezek', 'zvitek', 'zvok', 'zvonček', 'zvončnica', 'zvonec', 'zvonik', 'žaba', 'žabe', 'žad', 'žafran', 'žaga', 'žajbelj', 'žaloigra', 'žalost', 'Žalostinke', 'žamet', 'žanr', 'žara', 'žarek', 'žarišče', 'žebelj', 'žeja', 'želatina', 'žele', 'železnica', 'železo', 'želja', 'želo', 'želod', 'želodec', 'želva', 'žena', 'ženska', 'žep', 'žepar', 'žerjav', 'žetev', 'žezlo', 'žganjarna', 'žica', 'Žid', 'žila', 'žimnica', 'žirafa', 'žito', 'žival', 'živec', 'živež', 'živilo', 'živinozdravnik', 'življenje', 'življenjepis', 'življenjepisec', 'žleza', 'žlica', 'žoga', 'žolč', 'žolčnik', 'žolna', 'žongler', 'žrebe', 'žrebec', 'žrebica', 'žrtvovanje', 'žulj', 'župan', 'žuželka', 'žužkojed', 'žveplo'
]